### ISSUE TITLE
Error importing SFTPTarget with paramiko > 3.0

### ISSUE THREAD

**Issue by fralau** [mar10/pyftpsync#82]
When I import SFTPTarget (Python 3.10.11), I get the following error:

```
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/xxxx, line 15, in <module>
    from ftpsync.sftp_target import SFTPTarget
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ftpsync/sftp_target.py", line 50, in <module>
    class SFTPTarget(_Target):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ftpsync/sftp_target.py", line 385, in SFTPTarget
    _paramiko_py3compat_u = paramiko.py3compat.u
AttributeError: module 'paramiko' has no attribute 'py3compat'
```

Versions:
```
paramiko                    3.1.0
pyftpsync                   4.0.0
```

This works with paramiko==2.12.0, so this is is apparently a breaking change in that library.

**Comment by areddy-qontigo** [comment]
@mar10 It has been almost a year now. Can you please publish a new release?

**Comment by ChillarAnand** [comment]
@mar10 It has been almost a year now. Can you please publish a new release?
